services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    container_name: pgvector-db
    env_file:
      - ./env/pgvector-db.env
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    networks:
      - r2r_network
  unstructured:
    build:
      context: "./services/unstructured"
      dockerfile: "Dockerfile"
    container_name: unstructured
    ports:
      - "7275:7275"
    networks:
      - r2r_network
    restart: unless-stopped
volumes:
  postgres_data:
networks:
  r2r_network: