services:
  pgvector:
      image: 'pgvector/pgvector:pg16'
      container_name: pgvector
      environment:
        - 'POSTGRES_DB=r2r'
        - 'POSTGRES_USER=r00t'
        - 'POSTGRES_PASSWORD=t00r'
      ports:
        - '6666:5432'
      volumes:
        - 'postgres_data:/var/lib/postgresql/data'
volumes:
  postgres_data: