services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    container_name: pgvector-db
    env_file:
      - ./env/pgvector-db.env
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    networks:
      - r2r_network

  reranker:
    image: 'ghcr.io/huggingface/text-embeddings-inference:86-1.6'
    container_name: hf-reranker
    ports:
      - '8080:80'
    volumes:
      - 'reranker_data:/data'
    command: --model-id ${RE_RANKER_MODEL}
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    restart: unless-stopped
    networks:
      - r2r_network

volumes:
  postgres_data:
  reranker_data:

networks:
  r2r_network: