services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    container_name: pgvector-db
    env_file:
      - ./env/pgvector-db.env
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    networks:
      - r2r_network
volumes:
  postgres_data:
networks:
  r2r_network: