services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    container_name: pgvector
    environment:
      - POSTGRES_DB=${R2R_POSTGRES_DBNAME}
      - POSTGRES_USER=${R2R_POSTGRES_USER}
      - POSTGRES_PASSWORD=${R2R_POSTGRES_PASSWORD}
    ports:
      - '${R2R_POSTGRES_PORT:-5432}:5432'
    restart: unless-stopped
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    networks:
      - r2r_network
  unstructured:
    build:
      context: "./docker"
      dockerfile: "Dockerfile"
    container_name: unstructured
    ports:
      - "${UNSTRUCTURED_LOCAL_PORT:-7275}:7275"
    networks:
      - r2r_network
    restart: unless-stopped
volumes:
  postgres_data:
networks:
  r2r_network: