[agent]
tools = ["local_search"]

  [agent.generation_config]
  model = "ollama/llama3.1"

[logging]
level="DEBUG"

[app]
project_name = "bachelor"
default_max_documents_per_user = 1_000
default_max_chunks_per_user = 100_000
default_max_upload_size = 10_000_000 # 10 MB

fast_llm = "ollama_chat/llama3.1"    # LLM used for internal operations, like deriving conversation names
quality_llm = "ollama_chat/llama3.1" # LLM used for user-facing output, like RAG replies

# Reasoning model, used for `research` agent
reasoning_llm = "ollama_chat/llama3.1"
# Planning model, used for `research` agent
planning_llm = "ollama_chat/llama3.1"

[completion]
provider = "litellm"
concurrent_request_limit = 1

  [completion.generation_config]
  # https://docs.litellm.ai/docs/providers/ollama#using-ollama-apichat
  model = "ollama_chat/llama3.1"
  temperature = 0.1
  top_p = 1
  max_tokens_to_sample = 512
  stream = false

[completion_embedding]
provider = "litellm"
base_model = "ollama/mxbai-embed-large"
base_dimension = 1024
batch_size = 32
add_title_as_prefix = true
concurrent_request_limit = 2

# Have in mind that both r2r and re-ranker are containerized
# For that reason one can use the name of the containers instead of the urls
# Also note the port number
rerank_url = "http://hf-reranker:80"
rerank_model = "huggingface/BAAI/bge-reranker-large"

[database]
provider = "postgres"

[embedding]
provider = "litellm"
base_model = "ollama/mxbai-embed-large"
base_dimension = 1024
batch_size = 32
add_title_as_prefix = true
concurrent_request_limit = 2

[ingestion]
provider = "unstructured_local"
strategy = "auto"
chunking_strategy = "by_title"
new_after_n_chars = 512
max_characters = 1_024
combine_under_n_chars = 128
overlap = 0
chunk_overlap = 0
chunk_size = 512
chunks_for_document_summary = 16
document_summary_model = "ollama_chat/llama3.1"
automatic_extraction = false