[app]
project_name = "bachelor"
default_max_documents_per_user = 1_000
default_max_chunks_per_user = 100_000
default_max_upload_size = 10_000_000 # 10 MB

fast_llm = "ollama_chat/llama3.1:8b"    # LLM used for internal operations
quality_llm = "ollama_chat/llama3.1:8b" # LLM used for user-facing output, like RAG replies

[completion]
provider = "litellm"
# Make sure you check out your providers concurrency limits
# I believe that this value and the `OLLAMA_NUM_PARALLEL` must be the same
concurrent_request_limit = 1

  [completion.generation_config]
  # https://docs.litellm.ai/docs/providers/ollama#using-ollama-apichat
  model = "ollama_chat/llama3.1:8b"
  temperature = 0.0
  top_p = 1
  max_tokens_to_sample = 512
  stream = false

[completion_embedding]
provider = "litellm"
base_model = "ollama/mxbai-embed-large" # https://www.mixedbread.com/blog/mxbai-embed-large-v1
base_dimension = 1024 # This should match the base models dimension
batch_size = 32
add_title_as_prefix = true
concurrent_request_limit = 2

# Have in mind that both r2r and re-ranker are containerized
# For that reason one can use the name of the containers instead of the urls
# Also note the port number
rerank_url = "http://hf-reranker:80"
rerank_model = "huggingface/BAAI/bge-reranker-large"

[database]
provider = "postgres"

[embedding]
provider = "litellm"
base_model = "ollama/mxbai-embed-large" # https://www.mixedbread.com/blog/mxbai-embed-large-v1
base_dimension = 1024
batch_size = 32
add_title_as_prefix = true
concurrent_request_limit = 2

# https://unstructured.io/blog/chunking-for-rag-best-practices
[ingestion]
provider = "unstructured_local"  # Use the local instance that is running in a container
strategy = "hi_res"              # https://docs.unstructured.io/open-source/concepts/partitioning-strategies
chunking_strategy = "basic"      # https://docs.unstructured.io/api-reference/partition/chunking
new_after_n_chars = 1024         # Soft limit for chunk size (always max_characters)
max_characters = 1024            # Hard limit for chunk size (it can never exceed this value)
combine_text_under_n_chars = 512 # If chunks are smaller than this value, they will be combined (always max_characters / 2)
overlap = 128                    # chunk overlap 
chunk_size = 1024                # This is used for the RecursiveCharacterTextSplitter in case unstructured doesn't work (fallback)
chunk_overlap = 128              # This is used for the RecursiveCharacterTextSplitter in case unstructured doesn't work (fallback) 
skip_document_summary = true